

enum RouteNames {
    Splash = "Splash",
    Login = "Login",
    Otp = "Otp",
    SignUp = "SignUp",
    SignUpForm = "SignUpForm",
    HomeTabs = "HomeTabs",
    Browse = "Browse",
    DashBoard = "DashBoard",
    HomeNavigator = "HomeNavigator",
    BrowseNavigator = "BrowseNavigator",
    SpaceNavigator = "SpaceNavigator",
    LibraryNavigator = "LibraryNavigator",
    Main = "Main",
    Home = "Home",
    Spaces = "Spaces",
    UpgradeToSC = "UpgradeToSC",
    Profile = "Profile",
    EditProfile = "EditProfile",
    Hubs = "Hubs",
    SpaceDashBoard = "SpaceDashBoard",
    Content = "Content",
    ContentInfographicImage = "ContentInfographicImage",
        ContentGuidelinePdf = "ContentGuidelinePdf",
    SearchResult = "SearchResult",
    FollowersFollowing = "FollowersFollowing",
    UserSearch = "UserSearch",
    UserProfile = "UserProfile",
    History = "History",
    Downloads = "Downloads",
    CommentsScreen = "CommentsScreen",
    MyDirectory = "MyDirectory",
    Groups = "Groups",
    GroupName = "GroupName",
    NewGroup = "NewGroup",
    Favorites = "Favorites",
    SpaceCreation = "SpaceCreation",
    Collections="Collections",
    LibraryDashboard = "LibraryDashboard",
    FeaturedContentListing="FeaturedContentListing",
    DownloadedContent = "DownloadedContent",
    PrivacyScreen='PrivacyScreen',
    TermsConditionsScreen='TermsConditionsScreen'


}

export default RouteNames;